# Your project's server will run on localhost:xxxx at this port
PORT: 3001

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  sass:
    - "sass/diis-govcms.styles.scss"
    - "sass/diis-govcms.reset.scss"

DRUSH:
  enabled:
    - true
  alias: 
    cr:
      - "drush cc all"

