# Your project's server will run on localhost:xxxx at this port
PORT: 3001
PROXY: "http://localhost/govcms-7.x-2.14/"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  sass:
    - "sass/diisv3nisa.styles.scss"

DRUSH:
  enabled:
    - true
  alias:
    cr:
      - "drush cc all"
